### PR TITLE
feat: implement `pointToLineDistance`

### PR DESCRIPTION
**Pull request by mhammerc**
Hello,

I have implemented the `pointToLineDistance` function. The implementation and tests are adapted from Turf.js, and I have noted this in the source code. Please let me know if any additional steps are needed regarding this.

All tests have passed, and they match the ones used in Turf.js.

Please let me know if there are any issues or if anything needs to be adjusted.

Thank you for your work on the library!

### CODE REVIEW

**Review by lukas-h — APPROVED** [review]
looks good to me

**Comment by lukas-h** [comment]
Hey @mhammerc, I just reviewed – didn't find anything and will go ahead and merge.

**Comment by lukas-h** [comment]
Thanks a lot for your contribution :) @mhammerc

**Comment by mhammerc** [comment]
> Thanks a lot for your contribution :) @mhammerc

Thank you! :)

**Pull request merged**
