### PR TITLE
Feature nearest point on line

### PR DESCRIPTION
**Pull request by Just-gomin**
Add missing parameter 'unit' when calling "_nearestPointOnLine" in function "nearestPointOnLine".

### CODE REVIEW

**Comment by lukas-h** [comment]
Oh hi @Just-gomin, thanks for the addition, but the merge base branch should be `main`.

Sorry, I only just saw the PR.

Thanks for your contribution! 😄

**Comment by Just-gomin** [comment]
Thank you for your answer.

It was my first contribution, so I missed the 'merge base branch should be `main`' part.
I have created a new 'Pull Request' based on your advice.
I'd appreciate it if you could check it.

**Comment by lukas-h** [comment]
Thanks!

Yes, I will check.

**Comment by lukas-h** [comment]
Also, I'm closing this pull request in favor of #145.

**Pull request closed without merging**
