### PR TITLE
Add coverage reporting to pull requests tests

### PR DESCRIPTION
**Pull request by baparham**

### CODE REVIEW

**Comment by lukas-h** [comment]
Quick note: you first have to `dart pub global activate coverage` before running it 🙂

**Comment by baparham** [comment]
yeah, I'm kind of just experimenting with what is already activated and/or installed in the CI environment. Looks like I need to install lcov too if we want html, but that should be OK. If not, I am testing out a third party action to comment with the details we care about in the PR (https://github.com/marketplace/actions/code-coverage-report)

**Comment by baparham** [comment]
fixes #35

**Review by lukas-h — APPROVED** [review]
wow, that's great!

**Pull request merged**
