### PR TITLE
Refactor coordEach utilising geomEach internally // alternative approach to #57

### PR DESCRIPTION
**Pull request by lukas-h**
As described in my comment here:
https://github.com/dartclub/turf_dart/pull/57#issuecomment-1042943043
> I have built an implementation where I could get rid of many of the helper functions by implementing it internally with geomEach. I just wanted to test if that is possible, but seems to work. You can find it here:

in response to @tobrun's comment here: https://github.com/dartclub/turf_dart/pull/57#issue-1140349556
> This PR proposes the refactored code from https://github.com/dartclub/turf_dart/pull/50 to match geomEach setup.
> [...]
> Would you take a different approach?

what do you think?

### CODE REVIEW

**Review by tobrun — APPROVED** [review]
Looks great to me, might be good if we can run the benchmarks for both the old branch as this and see if there is a measurable difference

**Comment by lukas-h** [comment]
I will try to do it!

**Comment by lukas-h** [comment]
Branch `lukas-idea-coordeach-refactor`:

```
 coordEach
  ✓ geometry (0 us)
    Elapsed:    2 s
    Rounds:     2274999
    Iterations: 10
  ✓ feature (0 us)
    Elapsed:    2 s
    Rounds:     2581970
    Iterations: 10
  ✓ geometry collection (200 us)
    Elapsed:    2 s
    Rounds:     9994
    Iterations: 10
  ✓ feature collection (218 us)
    Elapsed:    2 s
    Rounds:     9137
    Iterations: 10
```

Branch `tvn-coordeach-refactor`:

```
coordEach
  ✓ geometry (0 us)
    Elapsed:    2 s
    Rounds:     3546893
    Iterations: 10
  ✓ feature (0 us)
    Elapsed:    2 s
    Rounds:     3860529
    Iterations: 10
  ✓ geometry collection (0 us)
    Elapsed:    2 s
    Rounds:     7164767
    Iterations: 10
  ✓ feature collection (102 us)
    Elapsed:    2 s
    Rounds:     19512
    Iterations: 10
```

Branch `main`:
```
 coordEach
  ✓ geometry (0 us)
    Elapsed:    2 s
    Rounds:     3125071
    Iterations: 10
  ✓ feature (0 us)
    Elapsed:    2 s
    Rounds:     3323376
    Iterations: 10
  ✓ geometry collection (0 us)
    Elapsed:    2 s
    Rounds:     3248169
    Iterations: 10
  ✓ feature collection (223 us)
    Elapsed:    2 s
    Rounds:     8942
    Iterations: 10
```

@tobrun

**Comment by lukas-h** [comment]
At the moment, it looks like, your version @tobrun is the fastest.

But I suspect, that you are skipping GeometryCollection altogether, which causes the `0 us` here. I may be wrong (https://github.com/dartclub/turf_dart/pull/57#discussion_r809031719)

**Comment by tobrun** [comment]
Let's go with this version!

**Pull request merged**
