### PR TITLE
Adds lineSlice method

### PR DESCRIPTION
**Pull request by leiflinse-trivector**
Issue: https://github.com/dartclub/turf_dart/issues/157

### CODE REVIEW

**Comment by leiflinse-trivector** [comment]
Rebased upon main

**Comment by leiflinse-trivector** [comment]
* Rebased upon main (along returns full Feature now)
* Changed parameters to lineSlice to be Feature<point> instead of just Point and updated testes for that
* I fixed the port where I inserted a guard for too short lines that shouldn't be there and caused the interpolation to fail in some cases.

I didn't have the time to retrofit changes due to main rebase back into the history so squashed it all together.

**Comment by jsiedentop** [comment]
Are you finished so that I can do a review?

**Comment by leiflinse-trivector** [comment]
I think it is ready for review.

I have a local test that uses along + lineSlice + length full circle and the accuracy isn't that great. (correct to 1%-level but not at 0,1%-level) But I read in turf.js some complaints about the accuracy of lineSlice so it might be related to that.

**Comment by leiflinse-trivector** [comment]
I can add that I did some testing with lineSlice, along and length that I wrote both in dart and in javascript to verify the port. So I am quite certain that the error-rate is from turf.js itself rather than the port.

**Comment by lukas-h** [comment]
@leiflinse-trivector I think this is good enough for a merge. 

@jsiedentop any objections? looking forward to the review

**Comment by leiflinse-trivector** [comment]
> @leiflinse-trivector I think this is good enough for a merge.

I agree.

**Comment by jsiedentop** [comment]
Since this project is a port of TurfJs, it is also legetim if we provide the same accuracy. Perhaps it would be good to mention the inaccuracy in the method description? We could also link to the TurfJs issue in the code.

@leiflinse-trivector was it [TurfJs - lineSlice is very imprecise #2023](https://github.com/Turfjs/turf/issues/2023) you were talking about?

**Review by lukas-h — APPROVED** [review]

**Comment by leiflinse-trivector** [comment]
> Since this project is a port of TurfJs, it is also legetim if we provide the same accuracy. Perhaps it would be good to mention the inaccuracy in the method description? We could also link to the TurfJs issue in the code.
> 
> @leiflinse-trivector was it [TurfJs - lineSlice is very imprecise #2023](https://github.com/Turfjs/turf/issues/2023) you were talking about?

Yes that is the complaints on turf.js that I was referring to. The tests I did myself have not been published there though.

**Pull request merged**
